/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2019-04-11 14:02:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1515100730856L));
    _jspx_dependants.put("jar:file:/C:/Users/Deepak/Selenium/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/web-volunteer-tracker/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323238578000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

out.println("<html>");
out.println("<head><meta http-equiv=Content-Type content=\"text/html; charset=UTF-8\">");
out.println("<style type=\"text/css\">");
out.println("<!--");
out.println("span.cls_007{font-family:\"Calibri Light\",serif;font-size:22.0px;color:rgb(46,83,149);font-weight:normal;font-style:normal;text-decoration: underline}");
out.println("div.cls_007{font-family:\"Calibri Light\",serif;font-size:22.0px;color:rgb(46,83,149);font-weight:normal;font-style:normal;text-decoration: none}");
out.println("span.cls_002{font-family:\"Calibri\",serif;font-size:11.1px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}");
out.println("div.cls_002{font-family:\"Calibri\",serif;font-size:11.1px;color:rgb(0,0,0);font-weight:normal;font-style:normal;text-decoration: none}");
out.println("span.cls_004{font-family:\"Calibri Bold\",serif;font-size:11.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}");
out.println("div.cls_004{font-family:\"Calibri Bold\",serif;font-size:11.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}");
out.println("span.cls_005{font-family:\"Calibri Bold\",serif;font-size:14.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}");
out.println("div.cls_005{font-family:\"Calibri Bold\",serif;font-size:14.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}");
out.println("span.cls_008{font-family:\"Calibri\",serif;font-size:11.1px;color:rgb(4,98,193);font-weight:normal;font-style:normal;text-decoration: underline}");
out.println("div.cls_008{font-family:\"Calibri\",serif;font-size:11.1px;color:rgb(4,98,193);font-weight:normal;font-style:normal;text-decoration: none}");
out.println("span.cls_009{font-family:\"Calibri Bold\",serif;font-size:11.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: underline}");
out.println("div.cls_009{font-family:\"Calibri Bold\",serif;font-size:11.1px;color:rgb(0,0,0);font-weight:bold;font-style:normal;text-decoration: none}");
out.println("-->");
out.println("</style>");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write(" function validateForm()\r\n");
      out.write("    {\r\n");
      out.write("\r\n");
      out.write("    var a = document.getElementById(\"name\");\r\n");
      out.write("    alert(name);\r\n");
      out.write("\r\n");
      out.write("   if(frm.name.value==\"\")\r\n");
      out.write("    {\r\n");
      out.write("      alert(\" Name can not be left blank\");\r\n");
      out.write("      frm.username.focus();\r\n");
      out.write("      return false;\r\n");
      out.write("    }\r\n");
      out.write("    return valid;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
out.println("</head>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"css/add-student-style.class\">\r\n");
 
out.println("<body>");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<form name=\"myForm\"  action=\"StudentControllerServlet\" method=\"POST\">\r\n");
      out.write("<input type=\"hidden\" name=\"command\" value=\"ADD\">\r\n");
      out.write("\r\n");
 
out.println("<div style=\"position:absolute;left:50%;margin-left:-306px;top:0px;width:612px;height:792px;border-style:outset;overflow:hidden\">");
out.println("<div style=\"position:absolute;left:0px;top:0px\">");

      out.write("\r\n");
      out.write("<div><img src=\"background1.jpg\" width=612 height=792></div>\r\n");
 
out.println("<div style=\"position:absolute;left:208.13px;top:123.38px\" class=\"cls_007\"><span class=\"cls_007\">Volunteer Registration</span></div>");
out.println("<div style=\"position:absolute;left:40.44px;top:175.22px\" class=\"cls_002\"><span class=\"cls_002\">Volunteer Name:");
      com.jdbc.connection.Student volunteer = null;
      volunteer = (com.jdbc.connection.Student) _jspx_page_context.getAttribute("volunteer", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (volunteer == null){
        volunteer = new com.jdbc.connection.Student();
        _jspx_page_context.setAttribute("volunteer", volunteer, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("volunteer"), request);
      out.write("<input type=\"text\"  name=\"name\" value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.jdbc.connection.Student)_jspx_page_context.findAttribute("volunteer")).getName())));
      out.write("\">   ");
out.println(" Date:");
      out.write("<input type=\"text\" disabled=\"true\" name=\"date\" value=\"");
      out.print( new java.util.Date() );
      out.write("\" >   ");
out.println(" </span></div>");
out.println("<div style=\"position:absolute;left:40.44px;top:197.66px\" class=\"cls_002\"><span class=\"cls_002\">Address:");
      out.write("<input type=\"text\"  name=\"address\" value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.jdbc.connection.Student)_jspx_page_context.findAttribute("volunteer")).getAddress())));
      out.write("\">   ");
out.println(" </span></div>");
out.println("<div style=\"position:absolute;left:40.44px;top:220.10px\" class=\"cls_002\"><span class=\"cls_002\">E-mail:");
      out.write("<input type=\"text\"  name=\"email\" value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.jdbc.connection.Student)_jspx_page_context.findAttribute("volunteer")).getEmail())));
      out.write("\">   ");
out.println(" </span></div>");
out.println("<div style=\"position:absolute;left:396.07px;top:220.10px\" class=\"cls_002\"><span class=\"cls_002\">Phone:");
      out.write("<input type=\"text\" required name=\"phonenum\" value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.jdbc.connection.Student)_jspx_page_context.findAttribute("volunteer")).getPhonenum())));
      out.write("\">   ");
out.println(" </span></div>");
out.println("<div style=\"position:absolute;left:250.07px;top:197.66px\" class=\"cls_002\"><span class=\"cls_002\">Volunteering Options:");
      out.write("<select name=\"volunteer_option\">     <option value=\"Turban Tying\">Turban Tying</option>     <option value=\"Line Management\">Line Management</option>     <option value=\"IT help\">IT help</option>     <option value=\"Turban Table\">Turban Table</option>     <option value=\"Volunteer check in table\">Volunteer check in table</option>     <option value=\"Interaction team in Langar\">Interaction team in Langar</option>     <option value=\"Others\">Others</option>     </select>  ");
out.println(" </span></div>");
out.println("<div style=\"position:absolute;left:40.44px;top:242.66px\" class=\"cls_002\"><span class=\"cls_002\">Volunteer Age (Please checkoff and encircle): ");
      out.write("<input type=\"radio\" name=\"ageu18\" value=\"ageu18\">");
out.println(" Under 18 years  or  ");
      out.write("<input type=\"radio\" name=\"agea18\" value=\"agea18\">  ");
out.print("  Over 18 years</span></div>");
out.println("<div style=\"position:absolute;left:40.44px;top:265.13px\" class=\"cls_004\"><span class=\"cls_004\">If volunteer is under 18 years of age:</span></div>");
out.println("<div style=\"position:absolute;left:40.44px;top:287.69px\" class=\"cls_002\"><span class=\"cls_002\">Parent or Legal Guardian Name :");
      out.write("<input type=\"text\" name=\"guardianname\" value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.jdbc.connection.Student)_jspx_page_context.findAttribute("volunteer")).getGuardianname())));
      out.write("\">   ");
out.println(" </span></div>");
out.println("<div style=\"position:absolute;left:40.44px;top:310.13px\" class=\"cls_002\"><span class=\"cls_002\">Parent or Legal Guardian E-mail:");
      out.write("<input type=\"text\" name=\"guardianemail\" value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.jdbc.connection.Student)_jspx_page_context.findAttribute("volunteer")).getGuardianemail())));
      out.write("\">   ");
out.println(" </span></div>");
out.println("<div style=\"position:absolute;left:40.44px;top:332.69px\" class=\"cls_002\"><span class=\"cls_002\">Parent or Legal Guardian Phone :");
      out.write("<input type=\"text\" name=\"guardianphone\" value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.jdbc.connection.Student)_jspx_page_context.findAttribute("volunteer")).getGuardianphone())));
      out.write("\">   ");
out.println(" </span></div>");
out.println("<div style=\"position:absolute;left:40.44px;top:355.13px\" class=\"cls_004\"><span class=\"cls_004\">Emergency Contact</span></div>");
out.println("<div style=\"position:absolute;left:42.96px;top:377.57px\" class=\"cls_002\"><span class=\"cls_002\">Name:");
      out.write("<input type=\"text\"  name=\"emergencycont\" value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.jdbc.connection.Student)_jspx_page_context.findAttribute("volunteer")).getEmergencycont())));
      out.write("\">   ");
out.println("  Relationship to Participant:");
      out.write("<input type=\"text\"  name=\"relationtype\" value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.jdbc.connection.Student)_jspx_page_context.findAttribute("volunteer")).getRelationtype())));
      out.write("\">   ");
out.println(" </span></div>");
out.println("<div style=\"position:absolute;left:40.44px;top:400.13px\" class=\"cls_002\"><span class=\"cls_002\">Phone Number:");
      out.write("<input type=\"text\"  name=\"relationph\" value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.jdbc.connection.Student)_jspx_page_context.findAttribute("volunteer")).getRelationph())));
      out.write("\">   ");
out.println(" </span></div>");
out.println("<div style=\"position:absolute;left:40.44px;top:422.59px\" class=\"cls_002\"><span class=\"cls_002\">Any allergies, medications, or other information needed in an emergency:</span></div>");
out.println("<div style=\"position:absolute;left:40.44px;top:437.11px\" class=\"cls_002\"><span class=\"cls_002\">");
      out.write("<input type=\"text\" name=\"allergies\" value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.jdbc.connection.Student)_jspx_page_context.findAttribute("volunteer")).getAllergies())));
      out.write("\">   ");
out.println(" </span></div>");
out.println("<div style=\"position:absolute;left:25.92px;top:481.75px\" class=\"cls_007\"><span class=\"cls_007\">VOLUNTEERS MUST COMPLETE THE WAIVER AND RELEASE FORM</span></div>");
out.println("<div style=\"position:absolute;left:245.21px;top:510.67px\" class=\"cls_007\"><span class=\"cls_007\">ON NEXT PAGE</span></div>");
out.println("<div style=\"position:absolute;left:16.32px;top:562.15px\" class=\"cls_007\"><span class=\"cls_007\">PARENT/LEGAL GUARDIAN SIGNATURE IS REQUIRED ON NEXT PAGE</span></div>");
out.println("<div style=\"position:absolute;left:169.94px;top:591.22px\" class=\"cls_007\"><span class=\"cls_007\">IF VOLUNTEER IS UNDER AGE 18</span></div>");
out.println("<div style=\"position:absolute;left:273.65px;top:643.06px\" class=\"cls_005\"><span class=\"cls_005\">Sikhs of NY</span></div>");
out.println("<div style=\"position:absolute;left:275.21px;top:661.42px\" class=\"cls_002\"><span class=\"cls_002\">767 Fifth Ave,</span></div>");
out.println("<div style=\"position:absolute;left:260.09px;top:675.94px\" class=\"cls_002\"><span class=\"cls_002\">New York, NY-10153</span></div>");
out.println("<div style=\"position:absolute;left:268.13px;top:690.46px\" class=\"cls_002\"><span class=\"cls_002\">+1-347.453.9786</span></div>");
out.println("<div style=\"position:absolute;left:254.69px;top:704.98px\" class=\"cls_008\"><span class=\"cls_008\"> </span><A HREF=\"mailto:contact@sikhsofny.org\">contact@sikhsofny.org</A> </div>");
out.println("<div style=\"position:absolute;left:303.29px;top:764.62px\" class=\"cls_002\"><span class=\"cls_002\">1</span></div>");
out.println("</div>");
out.println("</div>");
out.println("<div style=\"position:absolute;left:50%;margin-left:-306px;top:802px;width:612px;height:792px;border-style:outset;overflow:hidden\">");
out.println("<div style=\"position:absolute;left:0px;top:0px\">");
out.println("<img src=\"0f0a3140-386c-11e8-b174-0cc47a792c0a_id_0f0a3140-386c-11e8-b174-0cc47a792c0a_files/background2.jpg\" width=612 height=792></div>");
out.println("<div style=\"position:absolute;left:198.50px;top:40.92px\" class=\"cls_009\"><span class=\"cls_009\">Volunteer Release and Waiver of Liability Form</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:69.84px\" class=\"cls_002\"><span class=\"cls_002\">This Release and Waiver of Liability (the \"release\") executed on ");
      out.write("<input type=\"text\" name=\"volunteerDate\" value=\"");
      out.print( new java.util.Date() );
      out.write("\">   ");
out.println("\"(date) by \"");
out.println("");
      out.write(' ');
out.println("</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:84.38px\" class=\"cls_002\"><span class=\"cls_002\">(\"Volunteer\") releases \"</span><span class=\"cls_009\">Sikhs of NY</span><span class=\"cls_002\">\", (\"Nonprofit\"), a nonprofit corporation organized and existing under</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:98.90px\" class=\"cls_002\"><span class=\"cls_002\">the laws of the State of New York and each of its directors, officers, employees, and agents. The Volunteer</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:113.42px\" class=\"cls_002\"><span class=\"cls_002\">desires to provide volunteer services for Nonprofit and engage in activities related to serving as a</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:127.82px\" class=\"cls_002\"><span class=\"cls_002\">volunteer.</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:156.86px\" class=\"cls_002\"><span class=\"cls_002\">Volunteer understands that the scope of Volunteerâs relationship with Nonprofit is limited to a volunteer</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:171.38px\" class=\"cls_002\"><span class=\"cls_002\">position and that no compensation is expected in return for services provided by Volunteer; that</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:185.78px\" class=\"cls_002\"><span class=\"cls_002\">Nonprofit will not provide any benefits traditionally associated with employment to Volunteer; and that</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:200.30px\" class=\"cls_002\"><span class=\"cls_002\">Volunteer is responsible for his/her own insurance coverage in the event of personal injury or illness as a</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:214.82px\" class=\"cls_002\"><span class=\"cls_002\">result of Volunteerâs services to Nonprofit.</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:243.74px\" class=\"cls_009\"><span class=\"cls_009\">1. Waiver and Release:</span><span class=\"cls_002\"> I, the Volunteer, release and forever discharge and hold harmless Nonprofit and</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:258.29px\" class=\"cls_002\"><span class=\"cls_002\">its successors and assigns from any and all liability, claims, and demands of whatever kind of nature, either</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:272.81px\" class=\"cls_002\"><span class=\"cls_002\">in law or in equity, which arise or may hereafter arise from the services I provide to Nonprofit. I understand</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:287.33px\" class=\"cls_002\"><span class=\"cls_002\">and acknowledge that this Release discharges Nonprofit from any liability or claim that I may have against</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:301.73px\" class=\"cls_002\"><span class=\"cls_002\">Nonprofit with respect to bodily injury, personal injury, illness, death, or property damage that may result</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:316.25px\" class=\"cls_002\"><span class=\"cls_002\">from the services I provide to Nonprofit or occurring while I am providing volunteer services.</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:330.77px\" class=\"cls_009\"><span class=\"cls_009\">2. Insurance:</span><span class=\"cls_002\"> Further I understand that Nonprofit does not assume any responsibility for or obligation to</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:345.29px\" class=\"cls_002\"><span class=\"cls_002\">provide me with financial or other assistance, including but not limited to medical, health, or disability</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:359.69px\" class=\"cls_002\"><span class=\"cls_002\">benefits or insurance. I expressly waive any such claim for compensation or liability on the part of</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:374.21px\" class=\"cls_002\"><span class=\"cls_002\">Nonprofit beyond what may be offered freely by Nonprofit in the event of injury or medical expenses</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:388.73px\" class=\"cls_002\"><span class=\"cls_002\">incurred by me.</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:403.25px\" class=\"cls_009\"><span class=\"cls_009\">3. Medical Treatment:</span><span class=\"cls_002\"> I hereby Release and forever discharge Nonprofit from any claim whatsoever which</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:417.65px\" class=\"cls_002\"><span class=\"cls_002\">arises or may hereafter arise on account of any first-aid treatment or other medical services rendered in</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:432.19px\" class=\"cls_002\"><span class=\"cls_002\">connection with an emergency during my tenure as a volunteer with Nonprofit.</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:446.71px\" class=\"cls_009\"><span class=\"cls_009\">4. Assumption of Risk:</span><span class=\"cls_002\"> I understand that the services I provide to Nonprofit may include activities that</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:461.23px\" class=\"cls_002\"><span class=\"cls_002\">may be hazardous to me including, but not limited to exposure to rain/snow/inclement weather</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:475.63px\" class=\"cls_002\"><span class=\"cls_002\">conditions, lifting and transportation of heavy material involving inherently dangerous activities. As a</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:490.15px\" class=\"cls_002\"><span class=\"cls_002\">volunteer, I hereby expressly assume risk of injury or harm from these activities and Release Nonprofit</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:504.67px\" class=\"cls_002\"><span class=\"cls_002\">from all liability.</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:519.19px\" class=\"cls_009\"><span class=\"cls_009\">5. Photographic Release:</span><span class=\"cls_002\"> I grant and convey to Nonprofit all right, title, and interests in any and all</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:533.59px\" class=\"cls_002\"><span class=\"cls_002\">photographs, images, video, or audio recordings of me or my likeness or voice made by Nonprofit in</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:548.11px\" class=\"cls_002\"><span class=\"cls_002\">connection with my providing volunteer services to Nonprofit.</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:562.63px\" class=\"cls_009\"><span class=\"cls_009\">6. Other:</span><span class=\"cls_002\"> As a volunteer, I expressly agree that this Release is intended to be as broad and inclusive as</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:577.15px\" class=\"cls_002\"><span class=\"cls_002\">permitted by the laws of the State of New York and that this Release shall be governed by and interpreted</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:591.55px\" class=\"cls_002\"><span class=\"cls_002\">in accordance with the laws of the State of New York. I agree that in the event that any clause or provision</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:606.10px\" class=\"cls_002\"><span class=\"cls_002\">of this Release is deemed invalid, the enforceability of the remaining provisions of this Release shall not</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:620.62px\" class=\"cls_002\"><span class=\"cls_002\">be affected.</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:649.66px\" class=\"cls_002\"><span class=\"cls_002\">I express my understanding and intent to enter into this Release and Waiver of Liability</span></div>");
out.println("<div style=\"position:absolute;left:72.02px;top:664.06px\" class=\"cls_002\"><span class=\"cls_002\">willingly and voluntarily.");
      out.write("<input type=\"Submit\" value=\"I Agree\" class=\"save\"  onSubmit=\"return validateForm(this);\" /></form> class=\"save\"><a href=\"StudentControllerServlet\">Back to List</a>\r\n");
 out.println("</span></div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
out.println("<div style=\"position:absolute;left:303.29px;top:764.62px\" class=\"cls_002\"><span class=\"cls_002\">2</span></div>");
out.println("</div>");
out.println("");

      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
 
out.println("</body>");
out.println("</html>");

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
